- type: randomHumanoidSettings
  id: VisitorBrigmedic
  parent: VisitorSecurity
  components:
    - type: GhostRole
      name: job-name-brigmedic
      playTimeTracker: JobBrigmedic
      requirements:
        - !type:DepartmentTimeRequirement
          department: Security
          time: 36000 #10 hrs
        - !type:DepartmentTimeRequirement
          department: Medical
          time: 14400 #4 hrs
    - type: Loadout
      prototypes: [ VisitorBrigmedic, VisitorBrigmedicAlt ]
      roleLoadout: [ RoleSurvivalSecurity ]
      
- type: randomHumanoidSettings
  id: VisitorCourier
  parent: VisitorCargonian
  components:
    - type: GhostRole
      name: job-name-courier
      playTimeTracker: JobCourier
    - type: Loadout
      prototypes: [ VisitorCourier, VisitorCourierAlt ]
      roleLoadout: [ RoleSurvivalStandard ]

- type: randomHumanoidSettings
  id: VisitorRoboticist
  parent: VisitorScience
  components:
    - type: GhostRole
      name: job-name-roboticist
      playTimeTracker: JobScientist
    - type: Loadout
      prototypes: [ VisitorRoboticist, VisitorRoboticistAlt ]
      roleLoadout: [ RoleSurvivalStandard ]
