- type: entity
  parent: BaseItem
  id: BaseHandheldCriminalRecords
  name: portable criminal records
  description: All the power of a criminal records computer, but it fits in your pocket, or on your back!
  abstract: true
  components:
  - type: CriminalRecordsConsole
  - type: Sprite
    sprite: _Impstation/Objects/Devices/tablets.rsi
    layers:
      - state: portable_criminal
      - state: screen-criminal
        shader: unshaded
# THIS PART'S BROKEN I GUESS, LEMME SEE IF GITHUB SAYS ANYTHING
  - type: Clothing
    quickEquip: false
    sprite: _Impstation/Objects/Devices/tablet.rsi
    equippedPrefix: criminal
    slots:
    - suitStorage
# LIZARD CODE COMPARISON
#  - type: Clothing
#    quickEquip: false
#    sprite: Objects/Fun/toys.rsi
#    equippedPrefix: lizard
#    slots:
#    - HEAD
    clothingVisuals:
      suitStorage:
      - state: criminal-equipped-SUITSTORAGE
      - state: criminal-equipped-SUITSTORAGE-overlay
        shader: unshaded
  - type: ActivatableUI
    key: enum.CriminalRecordsConsoleKey.Key
  - type: UserInterface
    interfaces:
      enum.CriminalRecordsConsoleKey.Key:
        type: CriminalRecordsConsoleBoundUserInterface
  - type: Damageable
    damageContainer: Inorganic
  - type: Destructible
    thresholds:
      - trigger:
          !type:DamageTrigger
          damage: 100
        behaviors:
          - !type:DoActsBehavior
            acts: [ "Destruction" ]
  - type: AccessReader
    access: [["Security"]]
  - type: GuideHelp
    guides:
    - CriminalRecords

- type: entity
  id: HandheldCriminalRecords
  suffix: Powered
  parent:
  - BaseHandheldCriminalRecords
  - BaseHandheldComputer

- type: entity
  id: HandheldCriminalRecordsEmpty
  suffix: Empty
  parent:
  - BaseHandheldCriminalRecords
  - BaseHandheldComputer
  components:
  - type: ItemSlots
    slots:
      cell_slot:
        name: power-cell-slot-component-slot-name-default

- type: entity
  id: HandheldCriminalRecordsUnpowered
  suffix: Unpowered
  parent: BaseHandheldCriminalRecords
