- type: entity
  parent: BaseItem
  id: BaseHandheldCriminalRecords
  name: portable criminal records
  description: All the power of a criminal records computer, but it fits in your pocket, or on your back!
  abstract: true
  components:
  - type: CriminalRecordsConsole
  - type: Sprite
    sprite: _Impstation/Objects/Devices/tablets.rsi
    layers:
      - state: portable_criminal
      - state: screen-criminal
        shader: unshaded
  - type: Clothing
    quickEquip: false
    sprite: _Impstation/Objects/Devices/tablets.rsi
    equippedPrefix: criminal
    slots:
    - suitStorage
# THIS PART STILL ISN'T WORKING WITH THE UNSHADED LAYER, I'LL ASK RUDDYGREAT
    clothingVisuals:
      suitStorage:
      - state: criminal-equipped-SUITSTORAGE
      - state: criminal-equipped-SUITSTORAGE-overlay
        shader: unshaded
# RUDDYGREAT'S UNSHADED DEMO CODE COMPARISON
#  - type: Clothing
#    sprite: Clothing/Head/Hats/beret_engineering.rsi
#    clothingVisuals:
#      head:
#      - state: equipped-HELMET
#        shader: unshaded
  - type: ActivatableUI
    key: enum.CriminalRecordsConsoleKey.Key
  - type: UserInterface
    interfaces:
      enum.CriminalRecordsConsoleKey.Key:
        type: CriminalRecordsConsoleBoundUserInterface
  - type: Damageable
    damageContainer: Inorganic
  - type: Destructible
    thresholds:
      - trigger:
          !type:DamageTrigger
          damage: 100
        behaviors:
          - !type:DoActsBehavior
            acts: [ "Destruction" ]
  - type: AccessReader
    access: [["Security"]]
  - type: GuideHelp
    guides:
    - CriminalRecords

- type: entity
  id: HandheldCriminalRecords
  suffix: Powered
  parent:
  - BaseHandheldCriminalRecords
  - BaseHandheldComputer

- type: entity
  id: HandheldCriminalRecordsEmpty
  suffix: Empty
  parent:
  - BaseHandheldCriminalRecords
  - BaseHandheldComputer
  components:
  - type: ItemSlots
    slots:
      cell_slot:
        name: power-cell-slot-component-slot-name-default

- type: entity
  id: HandheldCriminalRecordsUnpowered
  suffix: Unpowered
  parent: BaseHandheldCriminalRecords
