- type: entity
  id: MailTeleporterMachineCircuitboard
  parent: [ BaseMachineCircuitboard, BaseCargoContraband ]
  name: mail telepad machine board
  description: A machine printed circuit board for a mail teleporter.
  components:
    - type: Sprite
      state: supply
    - type: MachineBoard
      prototype: MailTeleporter
      stackRequirements:
        Capacitor: 2
        Steel: 5
